schema_version: 1

context:
  name: debugpy
  version: "1.8.19"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: eea7e5987445ab0b5ed258093722d5ecb8bb72217c5c9b1e21f64efe23ddebdb

build:
  number: 0

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

tests:
  - python:
      imports:
        - debugpy
        - debugpy.adapter
        - debugpy.common
        - debugpy.launcher
        - debugpy.server
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyNotices.txt
  summary: An implementation of the Debug Adapter Protocol for Python
  homepage: https://github.com/Microsoft/debugpy
  repository: https://github.com/microsoft/debugpy

extra:
  recipe-maintainers:
    - jtilly
    - xhochy
